title: The Narrative Health Project
author: Gwen Haevens
email: gwen.haevens@gmail.com

baseurl: /ghaevens.github.io
collections:
  essays:
    output: true
  solutions:
    output: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap


repository: "ghaevens/ghaevens.github.io"

# A list of the pages to display in the navigation bar
header_pages:

show_excerpts: true
excerpt_separator: "<!--more-->"

# Exclude from processing.
# The following items will not be processed, by default.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - update_boostrap.sh
